### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by adalenv** [iamacarpet/vicidial-ws-agent-wallboard#1]
`/test/va # go build
main.go:6:5: cannot find package "github.com/codegangsta/negroni" in any of:
        /usr/lib64/go/src/pkg/github.com/codegangsta/negroni (from $GOROOT)
        ($GOPATH not set)
main.go:5:5: cannot find package "github.com/gorilla/mux" in any of:
        /usr/lib64/go/src/pkg/github.com/gorilla/mux (from $GOROOT)
        ($GOPATH not set)
agent_status_ws.go:10:5: cannot find package "github.com/gorilla/websocket" in any of:
        /usr/lib64/go/src/pkg/github.com/gorilla/websocket (from $GOROOT)
        ($GOPATH not set)
agent_status_ws.go:11:5: cannot find package "github.com/satori/go.uuid" in any of:
        /usr/lib64/go/src/pkg/github.com/satori/go.uuid (from $GOROOT)
        ($GOPATH not set)
agent_status.go:11:5: cannot find package "github.com/ziutek/mymysql/mysql" in any of:
        /usr/lib64/go/src/pkg/github.com/ziutek/mymysql/mysql (from $GOROOT)
        ($GOPATH not set)
agent_status.go:12:5: cannot find package "github.com/ziutek/mymysql/thrsafe" in any of:
        /usr/lib64/go/src/pkg/github.com/ziutek/mymysql/thrsafe (from $GOROOT)
`

**Comment by gunemalli** [comment]
If someone is having the same issues, this is what i did.

```
yum install golang -y
go get -v -u github.com/gorilla/mux github.com/codegangsta/negroni github.com/gorilla/websocket github.com/kennygrant/sanitize github.com/satori/go.uuid github.com/ziutek/mymysql/mysql github.com/ziutek/mymysql/thrsafe
go build
```

**Comment by iamacarpet** [comment]
Apologies guys, only just seen this.

Glad that works for you @gunemalli 

If you're on CentOS, you may find that the version of "go" from yum is very old, so it is usually recommended to grab the latest version from their website: https://golang.org/dl/

While you won't get automatic updates this way, you'll get a lot better performance and since Go is all statically compiled independently of libc (at least in the later versions), it doesn't depend on any other system packages, so shouldn't cause a problem with anything else.

Also, if you set up your go environment with a GOPATH, you can pull this repo using `go get` and it'll pull all the dependencies for you.

`go get -v github.com/iamacarpet/vicidial-ws-agent-wallboard`

**Comment by adalenv** [comment]
```
go get -v github.com/iamacarpet/vicidial-ws-agent-wallboard
can't load package: package github.com/iamacarpet/vicidial-ws-agent-wallboard: no Go files in /root/go/src/github.com/iamacarpet/vicidial-ws-agent-wallboard

```

**Comment by iamacarpet** [comment]
```
$ go get -v github.com/iamacarpet/vicidial-ws-agent-wallboard
github.com/iamacarpet/vicidial-ws-agent-wallboard (download)
github.com/codegangsta/negroni (download)
github.com/gorilla/websocket (download)
github.com/kennygrant/sanitize (download)
github.com/satori/go.uuid (download)
github.com/ziutek/mymysql (download)
golang.org/x/net/html/atom
github.com/ziutek/mymysql/mysql
golang.org/x/net/html
github.com/satori/go.uuid
github.com/codegangsta/negroni
github.com/gorilla/websocket
github.com/ziutek/mymysql/native
github.com/kennygrant/sanitize
github.com/ziutek/mymysql/thrsafe
github.com/iamacarpet/vicidial-ws-agent-wallboard
$
```

Just tried it and seems ok here in a blank GOPATH, could it be a problem with an outdated Go version?

EDIT:

I should say, first time I got an error:

```
# github.com/iamacarpet/vicidial-ws-agent-wallboard
../../../../iamacarpet/vicidial-ws-agent-wallboard/agent_status_ws.go:71:42: multiple-value uuid.NewV4() in single-value context
```

Looks like the UUID has had an update to return errors since this was written, so I've just commited a fix.

**Comment by adalenv** [comment]
`pbx_wallboard `not produced

**Comment by jerwin-fernandez** [comment]
im getting this error, 
package github.com/urfave/negroni
        imports github.com/urfave/negroni: import cycle not allowed

how can i fix this?
